[project]
name = "graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "gunicorn>=25.3.0",
    "jwt>=1.4.0",
    "langchain>=1.2.3",
    "langchain-experimental>=0.4.1",
    "langchain-groq>=1.1.1",
    "langchain-neo4j>=0.6.0",
    "pyjwt>=2.8.0",
    "pymupdf>=1.26.7",
    "python-dotenv>=1.2.1",
    "redis>=7.1.0",
    "requests>=2.32.5",
]
